version: '3.8'
services:
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTIC_PASSWORD: "password"
    ports:
      - '9200:9200'
    volumes: 
      - db:/var/lib/elasticsearch
volumes:
  db:
    driver: local
    external: false
