version: '3.8'
services:
  lola_postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - lola_postgres:/var/lib/postgresql/data
volumes:
  lola_postgres:
    driver: local
    external: false
